spring:
  application:
    name: Corner
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/corner_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
langchain4j:
  openai:
    chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: sk-1d01ad72852447b599e3baeea90be6a6
      model-name: deepseek-chat
      #开启log日志
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: sk-1d01ad72852447b599e3baeea90be6a6
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  expiration: 86400000

# 百度地图API配置
baidu:
  map:
    api-key: ${BAIDU_MAP_API_KEY:Fj18RcqBdN8w1lbYY7Rs32Kx6pW1Heru}
    geocoding-url: https://api.map.baidu.com/reverse_geocoding/v3/
    ip-location-url: https://api.map.baidu.com/location/ip

